### ISSUE TITLE
How does that work ? And how to make it work in Code::Block ?

### ISSUE THREAD

**Issue by MoccoU** [sneakyevilSK/IL2CPP_Resolver#15]
Hi,

**1 - How to make it work in Code::Block ?**

I created a new C++ Console project then in Project->Debug->Search Directories->Compiler, I clicked on Add and added the folder downloaded here containing all sources from IL2CPP_Resolver.

But I get errors like **_undefined reference to `IL2CPP::String::New(char const*)'_**

**2 - How does  IL2CPP_Resolver work ?**

I'm not a C++ programmer so I don't understand how this works. Do we need to compile a .DLL and inject it ? Does it find the Unity game process automatically?

If you could answer these two questions, it would be great and I think usefull to others too. Thanks.

**Comment by sneakyevilSK** [comment]
1. I didn't use Code Block for DLL stuff but I think it should be possible after including everything correctly.
2. The il2cpp Resolver is meant to be used as internal module (dll) not as external program (exe) which requires u to inject the dll to the process or you could also check my other project for hijacking dll and just make it load automatically by using hijacked dll, but that requires more work. So anyway you need to inject the dll by any injector.

**Comment by MoccoU** [comment]
Thanks for the explanation, I understand how it works now. Have a good day.
