### ISSUE TITLE
What software did you use ? How did you build the .dll ?

### ISSUE THREAD

**Issue by MoccoU** [sneakyevilSK/IL2CPP_Resolver#17]
Hi, its really not easy to know what to do with this source code, I tried Code::Block but failed, nothing worked.

Can you tell me what software did you use ? What compiler ? And how did you build the .dll ?

Thanks.

**Comment by sneakyevilSK** [comment]
It's really easy to use when you know how to use properly your IDE (I'm not here to help you with that, when its not even related to the project itself) and I personally use visual studio and all you need to do is just create directories as they are in default names and just include all of them (cpp files & header files) and thats all.

**Comment by MoccoU** [comment]
I will try visual studio, thanks. But maybe you should make a little guide in the Wiki section to explain how to configure a project in Visual for future people that could be interested :).
