### ISSUE TITLE
Trying to get value from field

### ISSUE THREAD

**Issue by kashiwazaki2** [sneakyevilSK/IL2CPP_Resolver#18]
Hey, first of all thank you for the library it is really good and easy to expand for your needs. Hoewer i am having an issue and i am not sure if it related to library or i am missing something, So i am trying to get the value from a Field of the game i am working on.

Here is the field i want to get, it is a member of ActorModel class (dnspy view)
![hp](https://user-images.githubusercontent.com/104969010/166875179-99b96c3a-c6bb-4cb2-b3af-58e6fd1a756b.png)

Here is how i am trying to retreive it on my proyect:
		
```
int GetHp()
		{
			if (!MemoryMgr::IsValidPtr(this))
				return 0;

			auto m_pFieldOffset = IL2CPP::Class::Utils::GetFieldOffset(xorstr_("ActorModel"), xorstr_("get_Hp"));
			printf("Hp Offset %i || ptr %p\r\n", *reinterpret_cast<int8_t*>(reinterpret_cast<uintptr_t>(this + m_pFieldOffset), reinterpret_cast<uintptr_t>(this) + m_pFieldOffset);
			return *reinterpret_cast<int8_t*>(this + m_pFieldOffset);
		}

		int GetHpMax()
		{
			if (!MemoryMgr::IsValidPtr(this))
				return 0;

			auto m_pFieldOffset = IL2CPP::Class::Utils::GetFieldOffset(xorstr_("ActorModel"), xorstr_("get_HpMax"));
			printf("Hp Offset %i || ptr %p\r\n", *reinterpret_cast<int8_t*>(reinterpret_cast<uintptr_t>(this + m_pFieldOffset), reinterpret_cast<uintptr_t>(this) + m_pFieldOffset);
			return *reinterpret_cast<int8_t*>(this + m_pFieldOffset);
		}
```

Once i call it from any ActorModel it dones't make any exception, it just give me an invalid value like this:

![Output](https://user-images.githubusercontent.com/104969010/166875765-0201c8b5-dfe8-4631-9cbd-544bc08a87e6.png)

Any help is appreciated, thank you!

**Comment by sneakyevilSK** [comment]
You're trying to get field offset, but you're using method name instead the field name which is "HpMax" and not "get_HpMax".

**Comment by kashiwazaki2** [comment]
> 

Well i tried both methods, but i tried it again after your reply just in case and it dones't work either, return the same weird value.

```
		int GetHp()
		{
			if (!MemoryMgr::IsValidPtr(this))
				return 0;

			auto m_pFieldOffset = IL2CPP::Class::Utils::GetFieldOffset(xorstr_("ActorModel"), xorstr_("Hp"));
			printf("Hp Offset %i || ptr %p\r\n", *reinterpret_cast<int*>(reinterpret_cast<uintptr_t>(this + m_pFieldOffset), reinterpret_cast<uintptr_t>(this) + m_pFieldOffset));
			return *reinterpret_cast<int*>(this + m_pFieldOffset);
		}

		int GetHpMax()
		{
			if (!MemoryMgr::IsValidPtr(this))
				return 0;

			auto m_pFieldOffset = IL2CPP::Class::Utils::GetFieldOffset(xorstr_("ActorModel"), xorstr_("HpMax"));
			printf("Hp Offset %i || ptr %p\r\n", *reinterpret_cast<int*>(reinterpret_cast<uintptr_t>(this + m_pFieldOffset), reinterpret_cast<uintptr_t>(this) + m_pFieldOffset));
			return *reinterpret_cast<int*>(this + m_pFieldOffset);
		}
```

**Comment by sneakyevilSK** [comment]
Maybe it is not field but it is property, otherwise you could fetch all fields and check if it even exist there otherwise it must be property.

**Comment by kashiwazaki2** [comment]
> Maybe it is not field but it is property, otherwise you could fetch all fields and check if it even exist there otherwise it must be property.

You are right bro i solved it thank you for your help, it was property as you said ^^
