### ISSUE TITLE
Is this still working ?

### ISSUE THREAD

**Issue by KaiFu0711** [sneakyevilSK/IL2CPP_Resolver#23]
I tried it in a Game and it was Initializing fine.. Then i tried the Substring loop or anything else and the game Crashed.

**Comment by Toxocious** [comment]
Were you trying on an x64 game or a x86 game?

Initializing works fine on x86 (32-bit) but will crash the game if you attempt to do use any of the functionality of it afterwards.

**Comment by KaiFu0711** [comment]
I was trying on a x64 game here my code
![image](https://user-images.githubusercontent.com/82840369/203656474-e26c1b90-845a-4a12-8526-60282d7e70b9.png)

**Comment by KaiFu0711** [comment]
update functions is empty

**Comment by KaiFu0711** [comment]
![image](https://user-images.githubusercontent.com/82840369/203661167-0ede91b8-3cfe-42b7-92ce-a9a64e167de4.png)
