### ISSUE TITLE
How to get the member variables of PlayerControll

### ISSUE THREAD

**Issue by LanBaiCode** [sneakyevilSK/IL2CPP_Resolver#24]
I have tried many methods, but none of them can get the health variable correctly

Here is my injection code:
![image](https://user-images.githubusercontent.com/72244576/209565911-28025015-3f52-47d6-a03b-49e2f74cb1db.png)

This is log:
![image](https://user-images.githubusercontent.com/72244576/209565976-74c4ba92-1b54-41a8-8d01-260b5683adf5.png)

This is the health variable at runtime:
![image](https://user-images.githubusercontent.com/72244576/209566091-3da1cbd6-1a6b-4c6d-bc9f-d5af3225a836.png)

dump.cs:
![image](https://user-images.githubusercontent.com/72244576/209566172-8ba228b8-1540-40e3-ae1c-5ad66678e87a.png)
![image](https://user-images.githubusercontent.com/72244576/209566151-110c19a1-a279-4028-ba82-d2c7c7326105.png)

**Comment by sneakyevilSK** [comment]
You trying to get field value but you call GetComponent...
Use "GetMemberValue".

**Comment by LanBaiCode** [comment]
> 您试图获取字段值但调用了 GetComponent... 使用“GetMemberValue”。

Is there an example

**Comment by LanBaiCode** [comment]
> You trying to get field value but you call GetComponent... Use "GetMemberValue".

Is there an example

**Comment by LanBaiCode** [comment]
> You trying to get field value but you call GetComponent... Use "GetMemberValue".

Do you have any other contact information, I am recently studying this project and would like to discuss it.

**Comment by sneakyevilSK** [comment]
> Do you have any other contact information, I am recently studying this project and would like to discuss it.

I won't discuss anything around this project, read the src or public wiki. 
If you struggling with that then don't even bother using this project, or better to say: learn c++ and learn unity.
