### ISSUE TITLE
86 Crashes

### ISSUE THREAD

**Issue by xo1337** [sneakyevilSK/IL2CPP_Resolver#4]
Hey there, this project is pretty amazing (great work on it!), I've used this on many il2cpp game then tried using it on BLOCKPOST (x86 il2cpp), and when calling the initialize function i get a crash. So i went to go change the calling convention from `__fastcall` to `__cdecl` and it seemed to fix the crash. But then i am not able to get the camera main or use any other functions. Any ideas?

**Comment by sneakyevilSK** [comment]
Hey,

Did you change the calling convention for IL2CPP & Unity funcs?

https://github.com/sneakyevilSK/IL2CPP_Resolver/blob/main/Defines.hpp#L32
https://github.com/sneakyevilSK/IL2CPP_Resolver/blob/main/Unity/Defines.hpp#L3

Also you should step through the init func and check if exports are even found correctly.

**Comment by sneakyevilSK** [comment]
Closing this as no comment after 20 days.
