### ISSUE TITLE
(question) how can i change texture of material to my texture loaded from .png file

### ISSUE THREAD

**Issue by SVO-ARBUZ** [sneakyevilSK/IL2CPP_Resolver#58]
### What is the game you are using with IL2CPP Resolver?

SCP:SL

### Details:

how can i change texture of material to my texture loaded from .png file, i tried before but i get black texture

**Comment by eeacks** [comment]
this question not related to this library, you should search in google for example "how to load texture in unity"
then you reimplement with il2cppresolver.

**Comment by SVO-ARBUZ** [comment]
I would do this with pleasure, but there is very little information in the documentation, for example, I did not understand which method performs the equivalent of this C# code new Texture2D(50,50);

**Comment by eeacks** [comment]
[il2cpp_new_object with il2cppclass](https://github.com/sneakyevil/IL2CPP_Resolver/blob/251051e4f2f6b2b6f3a8169d65f3739317e1de08/Unity/API/Object.hpp#L38)

**Comment by SVO-ARBUZ** [comment]
I'll try not to ask any more questions like this and put everything in this comment. I don't understand how to pass arguments (50,50) and if they can be passed at all, I don't understand how to call methods in a new object to change fields, etc. I don't understand how I can assign this new object to an existing material.

**Comment by eeacks** [comment]
```cpp
auto c = (Unity::CComponent*)Unity::Object::New(your_class);
auto c1 = (Unity::CComponent*)Unity::Object::New(your_class1);

// constructor
c->CallFunction<>(".ctor");

c->SetMemberValue<your_type>("your_field", field_data);
c1->SetMemberValue<your_type1>("your_field", c);
```

pseducode btw dont paste that, the documentation of the library isnt even proper, but its not hard to do anything. almost everything here is just some pointer-like bullshit. you new with that cast to component and set field then put in another field... just stacking them.
constructor is like `.ctor()` or `.cctor` iirc, i dont really remember, since long time without doing new thing.
