### ISSUE TITLE
Issuse with ->FetchMethods(&methods); 

### ISSUE THREAD

**Issue by lyxgitgo** [sneakyevilSK/IL2CPP_Resolver#59]
### What is the game you are using with IL2CPP Resolver?

-

### Details:

std::vector<Unity::il2cppMethodInfo*> methods;
component->FetchMethods(&methods);
for (int k = 0; k < methods.size(); k++) {
				auto method = methods[k];
				fprintf(file, "\t\t\tMethod - %s\n", method->m_pName);		
}
got these:
Method - H嬃I嬋H嗵烫烫烫I婣L嬄I婹L嬔I?M婭L塂$(??D?
Method - H冹8I嬂L嬌L嬄H峀$ H嬓A袶婰$`?
Method - H冹8I?M嬝L嬔L嬄H峊$ I嬎?
Method - H冹8I嬂L嬌L嬄H峀$ H嬓A袶婰$`?

Then I tryed ->FetchFields(&vect); It is OK
Field - _lastFrameTime
Field - JUDGE_DEBUG_TIME

**Comment by eeacks** [comment]
use il2cppdumper and generate dump.cs, and check dump.cs. everything in alternate way is use offset.
https://github.com/Perfare/Il2CppDumper
