### ISSUE TITLE
 Dictionary class?)

### ISSUE THREAD

**Issue by fork1488** [sneakyevilSK/IL2CPP_Resolver#6]
![image](https://user-images.githubusercontent.com/87487867/148702340-30609c79-906f-4843-8055-23dc945644e0.png)

```
`template<typename T, typename N>
	struct il2cppDictionary : il2cppObject
	{
        void* buckets;
        void* entries;
        int32_t count;
        int32_t version;
        int32_t freeList;
        int32_t freeCount;
        void* comparer;
        void* keys;
        void* values;
        int32_t _syncRoot;
	};`
```
	
	sorry not full, go sleeping

**Comment by extremeblackliu** [comment]
currently we are working on it

**Comment by fork1488** [comment]
> currently we are working on it

![image](https://user-images.githubusercontent.com/87487867/148960662-aa6d19c8-ae2a-4946-923e-d3aad41ffab1.png)
C# HashSet<type>
`  <Element Offset="40" Vartype="Pointer" Bytesize="8" OffsetHex="00000028" Description="entities" DisplayMethod="Unsigned Integer">
    <Structure Name="Autocreated from 1C9CCA13FA0" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
      <Elements>
        <Element Offset="16" Vartype="Pointer" Bytesize="8" OffsetHex="00000010" Description="_buckets" DisplayMethod="Unsigned Integer"/>
        <Element Offset="24" Vartype="Pointer" Bytesize="8" OffsetHex="00000018" Description="_slots" DisplayMethod="Unsigned Integer"/>
        <Element Offset="32" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000020" Description="_count" DisplayMethod="Unsigned Integer"/>
        <Element Offset="36" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000024" Description="_lastIndex" DisplayMethod="Unsigned Integer"/>
        <Element Offset="40" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000028" Description="_freeList" DisplayMethod="Unsigned Integer"/>
        <Element Offset="48" Vartype="Pointer" Bytesize="8" OffsetHex="00000030" Description="_comparer" DisplayMethod="Unsigned Integer"/>
        <Element Offset="56" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000038" Description="_version" DisplayMethod="Unsigned Integer"/>
        <Element Offset="64" Vartype="Pointer" Bytesize="8" OffsetHex="00000040" Description="_siInfo" DisplayMethod="Unsigned Integer"/>
      </Elements>
    </Structure>
  </Element>
</Elements>`

**Comment by Rednick16** [comment]
```cpp
template <typename T>
struct Il2CppArray
{
    void* klass;
    void* monitor;
    void* bounds;
    int   max_length;
    void* vector [1];
    int getLength()
    {
        return max_length;
    }
    T getPointer()
    {
        return (T)vector;
    }
};

template<typename K, typename V> 
struct Il2CppDictionary {
    Il2CppClass *klass;
    void *unk1;
    Il2CppArray<int **> *table;
    Il2CppArray<void **> *linkSlots;
    Il2CppArray<K> *keys;
    Il2CppArray<V> *values;
    int touchedSlots;
    int emptySlot;
    int size;

    K *getKeys() {
        return keys->getPointer();
    }

    V *getValues() {
        return values->getPointer();
    }

    int getNumKeys() {
        return keys->getLength();
    }

    int getNumValues() {
        return values->getLength();
    }

    int getSize() {
        return size;
    }
};
```

**Comment by S3eeD2** [comment]
> ```c++
> template <typename T>
> struct Il2CppArray
> {
>     void* klass;
>     void* monitor;
>     void* bounds;
>     int   max_length;
>     void* vector [1];
>     int getLength()
>     {
>         return max_length;
>     }
>     T getPointer()
>     {
>         return (T)vector;
>     }
> };
> 
> template<typename K, typename V> 
> struct Il2CppDictionary {
>     void* klass;
>     void *unk1;
>     Il2CppArray<int **> *table;
>     Il2CppArray<void **> *linkSlots;
>     Il2CppArray<K> *keys;
>     Il2CppArray<V> *values;
>     int touchedSlots;
>     int emptySlot;
>     int size;
> 
>     K *getKeys() {
> ```

Rename everything and put it here as yours without giving credit to whoever wrote it, very bad behavior.

This struct written by **caoyin**, [this link](https://github.com/Karveit/UnityStuff-1/blob/master/Unity.h) to the original file.

**Comment by Rednick16** [comment]
> ```c++
> ```c++
> template <typename T>
> struct Il2CppArray
> {
>     void* klass;
>     void* monitor;
>     void* bounds;
>     int   max_length;
>     void* vector [1];
>     int getLength()
>     {
>         return max_length;
>     }
>     T getPointer()
>     {
>         return (T)vector;
>     }
> };
> 
> template<typename K, typename V> 
> struct Il2CppDictionary {
>     void* klass;
>     void *unk1;
>     Il2CppArray<int **> *table;
>     Il2CppArray<void **> *linkSlots;
>     Il2CppArray<K> *keys;
>     Il2CppArray<V> *values;
>     int touchedSlots;
>     int emptySlot;
>     int size;
> 
>     K *getKeys() {
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Rename everything and put it here as yours without giving credit to whoever wrote it, very bad behavior.
> This struct written by caoyin, this link to the original file.
> ```

Did you want an answer?

**Comment by Rednick16** [comment]
> ```c++
> ```c++
> template <typename T>
> struct Il2CppArray
> {
>     void* klass;
>     void* monitor;
>     void* bounds;
>     int   max_length;
>     void* vector [1];
>     int getLength()
>     {
>         return max_length;
>     }
>     T getPointer()
>     {
>         return (T)vector;
>     }
> };
> 
> template<typename K, typename V> 
> struct Il2CppDictionary {
>     void* klass;
>     void *unk1;
>     Il2CppArray<int **> *table;
>     Il2CppArray<void **> *linkSlots;
>     Il2CppArray<K> *keys;
>     Il2CppArray<V> *values;
>     int touchedSlots;
>     int emptySlot;
>     int size;
> 
>     K *getKeys() {
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Rename everything and put it here as yours without giving credit to whoever wrote it, very bad behavior.
> This struct written by caoyin, this link to the original file.
> ```

well that one wasn't made by me I took it from someone else in a hurry I hope u can understand lmao here's my own:
https://github.com/Rednick16/IL2Cpp-Dictionary

**Comment by extremeblackliu** [comment]
its been 1 year, added to pr, close later

**Comment by sneakyevilSK** [comment]
Added in latest commit: 3967263271f5616b4ba97bf9d01e594cf7112194
