### ISSUE TITLE
Why header only

### ISSUE THREAD

**Issue by 0NullBit0** [sneakyevilSK/IL2CPP_Resolver#63]
### What is the game you are using with IL2CPP Resolver?

any

### Details:

Why did u guys make it header only its bad for projects which work with more than one cpp file very annoying to have all code in headers...

**Comment by TrippleAWap** [comment]
Ever heard of pch??

**Comment by 0NullBit0** [comment]
yes i dont vant precompiled header because i change il2cpp resolver often  so ive actually fixed this by doing necessary inline definitions so im closing this

**Comment by tikkamasala** [comment]
> Ever heard of pch??

How does including IL2CPP_Resolver.hpp in pch.h solve the issue of having functions defined everywhere you include pch.h ? I'm having the same problem as OP and I don't usually do C++ but from what ChatGPT/Deepseek said, including the hpp in pch.h won't solve the multiple definitions and linking errors.

**Comment by 0NullBit0** [comment]
will take some time but you have to change the definitions inside every header to be inline so you can actually use it as a header only library properly
